#!/usr/bin/env bash

# 1. Load the prompt library
PROMPT_DIR="./bash_prompt.d"
for f in "$PROMPT_DIR"/*.sh; do
  [ -r "$f" ] && source "$f"
done

# 2. Define segments, region assignments & prompt color
segments=(
  "path|📁|render_path_x|none:gray:olive:gray"
  "git|🌿|render_git_x|none:brown+bold:gray:lime?coral:gray"
  "user|👤|render_user|blue"
  "host|🖥️:2|render_host|purple"
  "time|🕐|render_time_x|turquoise:none:coral"
)
left="path|git"
center="time"
right="user|host"
prompt="orange"

# 3. Initialize the prompt
prompt_init segments "$left" "$center" "$right" "$prompt"
