#!/usr/bin/env bash

PROMPT_DIR="./bash_prompt.d"

for f in "$PROMPT_DIR"/*.sh; do
  [ -r "$f" ] && source "$f"
done

segments=(
  "path|📁|render_path|none:gray:yellow:gray"
  "git|🌿|render_git|none:green+bold:gray:bright_green?red:gray"
  "user|👤|render_user|blue"
  "host|🖥️|render_host|orange"
  "time|🕐|render_time_complex|white:none:white"
)
left="path|git"
center="time"
right="user|host"
prompt="orange"

prompt_init segments "$left" "$center" "$right" "$prompt"
