#!/usr/bin/env bash

PROMPT_DIR="./bash_prompt.d"

for f in "$PROMPT_DIR"/*.sh; do
  [ -r "$f" ] && source "$f"
done

segments=(
  "path|📁|render_path|none:gray:olive:gray"
  "git|🌿|render_git|none:brown+bold:gray:lime?coral:gray"
  "user|👤|render_user|blue"
  "host|🖥️:2|render_host|gray"
  "time|🕐|render_time_complex|turquoise:none:coral"
)
left="path|git"
center="time"
right="user|host"
prompt="orange"

prompt_init segments "$left" "$center" "$right" "$prompt"
