#!/usr/bin/env bash
# Generated by Codex on Fri Feb  6 10:23:38 CST 2026.
set -euo pipefail

SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TARGET_PROMPT="$HOME/.bash_prompt"
TARGET_DIR="$HOME/.bash_prompt.d"

backup_if_exists() {
  local path="$1"
  if [[ -e "$path" ]]; then
    rm -rf "${path}.bak.3"
    if [[ -e "${path}.bak.2" ]]; then
      mv "${path}.bak.2" "${path}.bak.3"
    fi
    if [[ -e "${path}.bak.1" ]]; then
      mv "${path}.bak.1" "${path}.bak.2"
    fi
    mv "$path" "${path}.bak.1"
  fi

  for backup in "${path}".bak.*; do
    [[ -e "$backup" ]] || continue
    case "$backup" in
      "${path}.bak.1"|"${path}.bak.2"|"${path}.bak.3") ;;
      *) rm -rf "$backup" ;;
    esac
  done
}

if [[ ! -f "$SRC_DIR/bash_prompt" ]]; then
  printf "Error: missing %s\n" "$SRC_DIR/bash_prompt" >&2
  exit 1
fi
if [[ ! -d "$SRC_DIR/bash_prompt.d" ]]; then
  printf "Error: missing %s\n" "$SRC_DIR/bash_prompt.d" >&2
  exit 1
fi

backup_if_exists "$TARGET_PROMPT"
backup_if_exists "$TARGET_DIR"

cp -f "$SRC_DIR/bash_prompt" "$TARGET_PROMPT"
cp -a "$SRC_DIR/bash_prompt.d" "$TARGET_DIR"

sed -i 's|^PROMPT_DIR=.*|PROMPT_DIR="$HOME/.bash_prompt.d"|' "$TARGET_PROMPT"

SOURCE_LINE='[ -r "$HOME/.bash_prompt" ] && source "$HOME/.bash_prompt"'

printf "Installed prompt to %s and %s\n" "$TARGET_PROMPT" "$TARGET_DIR"
printf "Backups (if any) saved as .bak.1 ... .bak.3\n"
printf "Add this to your shell config if desired:\n  %s\n" "$SOURCE_LINE"
