#!/usr/bin/env bash

segments=(
  "path|📁|render_path_x|none:gray:olive:gray"
  "git|🌿|render_git_x|none:brown+bold:gray:lime?coral:gray"
  "user|👤|render_user|blue"
  "host|🖥️:2|render_host|purple"
  "time|🕐|render_time_x|turquoise:none:coral"
)

left="path|git"
center="time"
right="user|host"
prompt_color="orange"
